project_id = "ipkugzwdhrbnqvwgxven"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["tolk-og-laer://**"]

[realtime]
enabled = true
